server:
  port: 8080
  origin: "http://localhost:8080"
postgres:
  host: localhost
  port: 5432
  username: postgres
  password: password
  database: chat_socio
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  database: 0

websocket:
  origin: "http://localhost:8080"

jwt:
  secret: "ASDWRTGHJKLQWERTYUIOPZXCVBNMASDFGHJKLQWERTYUIOPZXCVBNM"
  issuer: "chat_socio"
  expiration: 3600

nats:
  address: "nats://localhost:4222"
